spring:
  application:
    name: myretail
  data:
    cassandra:
      keyspace-name: myretail
      contact-points: localhost
externalApiURL: "http://redsky.target.com/v2/pdp/tcin"
externalApiParams: "?excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics"
logging: 
  level:
    ROOT: INFO
    
hystrix:
    threadpool.default.coreSize: 20
    threadpool.HystrixThreadPoolKey.coreSize: 20
    command:
        redSkyCmdKey:
           sleepWindowInMilliseconds: 5000
           requestVolumeThreshold: 20
           errorThresholdPercentage: 50
           execution.isolation.thread.timeoutInMilliseconds: 20000
      